import streamlit as st
import pandas as pd
from database import get_db_connection
from fpdf import FPDF

def generate_pdf(name, file_name, score):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, "RTU StudyStream - Examination Result", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, f"Student Name: {name}", ln=True)
    pdf.cell(200, 10, f"Assessment: {file_name}", ln=True)
    pdf.cell(200, 10, f"Final Score: {score}/30", ln=True)
    pdf.ln(10)
    pdf.cell(200, 10, "Congratulations on completing your assessment!", ln=True, align='C')
    return pdf.output(dest='S').encode('latin-1')

def show_student_dashboard(user_data):
    # --- 1. FULLSCREEN ASSESSMENT MODE ---
    # This block triggers when the student clicks "Start AI Assessment"
    if st.session_state.get("quiz_active", False):
        st.markdown(f'<div class="rtu-header"><h1>Assessment: {st.session_state.current_exam_file}</h1></div>', unsafe_allow_html=True)
        
        conn = get_db_connection()
        if conn:
            cursor = conn.cursor(dictionary=True)
            # Fetch the 30 questions generated by the Admin
            cursor.execute("SELECT * FROM mdl_quiz_questions WHERE file_name = %s", (st.session_state.current_exam_file,))
            questions = cursor.fetchall()
            
            if questions:
                with st.container():
                    st.info("Instructions: Read each question carefully and provide your answer in the text box provided.")
                    
                    # Display all 30 items
                    for i, q in enumerate(questions):
                        st.write(f"### Question {i+1}")
                        st.write(q['question_text'])
                        st.text_input("Enter your response:", key=f"ans_{i}", placeholder="Type answer here...")
                        st.divider()
                
                # Submission Controls
                col1, col2 = st.columns([1, 5])
                with col1:
                     if st.button("Submit Exam", type="primary", use_container_width=True):
                        st.balloons()
                        st.success("Exam submitted successfully!")
                        
                        # Generate the PDF data
                        pdf_data = generate_pdf(user_data['firstname'], st.session_state.current_exam_file, 28)
                        
                        # Show the download button
                        st.download_button(
                            label="Download Result PDF",
                            data=pdf_data,
                            file_name=f"Result_{st.session_state.current_exam_file}.pdf",
                            mime="application/pdf"
                        )
                with col2:
                    if st.button("Exit without Saving", help="Warning: Your progress will be lost"):
                        st.session_state.quiz_active = False
                        st.rerun()
            else:
                st.error("No questions found for this exam. Please contact your instructor.")
                if st.button("Go Back"):
                    st.session_state.quiz_active = False
                    st.rerun()
            conn.close()

    # --- 2. REGULAR DASHBOARD VIEW ---
    else:
        st.markdown(f'<div class="rtu-header"><h1> Welcome, {user_data.get("firstname", "Student")}!</h1><p>RTU Student Learning Portal</p></div>', unsafe_allow_html=True)
        
        tab_learn, tab_mock = st.tabs(["Learning Materials Hub", "AI Mock Exams"])

        with tab_learn:
            st.header("Academic Resources")
            st.write("Access your lecture notes and official course documents below.")
            
            col_a, col_b = st.columns(2)
            with col_a:
                st.info("**Document Library**")
                # These are static features as requested
                st.button("IT 401: Systems Integration Syllabus.pdf", use_container_width=True)
                st.button("Database Management Reviewer.pdf", use_container_width=True)
            
            with col_b:
                st.info("**Video Lectures**")
                st.button("Watch: SQL Fundamentals & Joins", use_container_width=True)
                st.button("Watch: Python Streamlit for BSIT", use_container_width=True)

        with tab_mock:
            st.header("AI-Generated Assessments")
            st.write("Test your knowledge by taking a mock exam based on your instructor's reviewers.")
            
            conn = get_db_connection()
            if conn:
                # READ: Fetch distinct files that have quizzes available
                df_exams = pd.read_sql("SELECT DISTINCT file_name FROM mdl_quiz_questions", conn)
                
                if not df_exams.empty:
                    st.success(f"There are {len(df_exams)} assessments currently published.")
                    selected = st.selectbox("Select a Subject / Reviewer to start:", df_exams['file_name'])
                    
                    st.warning("Once you start, the navigation will be locked until you submit or exit.")
                    if st.button("Start AI Assessment", use_container_width=True):
                        st.session_state.quiz_active = True
                        st.session_state.current_exam_file = selected
                        st.rerun()
                else:
                    st.info("No exams have been published yet. Check back soon!")
                conn.close()